# Generated by Django 3.2.6 on 2021-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('photo', models.ImageField(upload_to='flowers_img/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=100, verbose_name='Дом')),
                ('latitude', models.CharField(max_length=100, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=100, verbose_name='Долгота')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=models.SET(0), to='django_app.manager', verbose_name='Идентификатор Менеджера')),
                ('store', models.ForeignKey(on_delete=models.SET(0), to='django_app.store', verbose_name='Идентификатор магазина')),
            ],
            options={
                'verbose_name': 'Рассылка менеджеру',
                'verbose_name_plural': 'Рассылки менеджерам',
            },
        ),
        migrations.CreateModel(
            name='ProductInStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=models.SET(0), to='django_app.product', verbose_name='Идентификатор Товара')),
                ('store', models.ForeignKey(on_delete=models.SET(0), to='django_app.store', verbose_name='Идентификатор магазина')),
            ],
            options={
                'verbose_name': 'Товар в магазине',
                'verbose_name_plural': 'Товары в магазине',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('shipping_address', models.CharField(max_length=100, verbose_name='Адрес Доставки')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('successful', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('customer_id', models.ForeignKey(on_delete=models.SET(0), to='django_app.customer', verbose_name='Покупатель')),
                ('product_id', models.ForeignKey(on_delete=models.SET(0), to='django_app.product', verbose_name='Идентификатор Товара')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
